# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\WinSys\PROJECTS\WORMCHAN\WormChan\WormChan\APP\app_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 1172)
        MainWindow.setMinimumSize(QtCore.QSize(984, 1036))
        MainWindow.setStyleSheet(
            "/*\n"
            "AMOLED Style Sheet for QT Applications\n"
            "Author: Jaime A. Quiroga P.\n"
            "Company: GTRONICK\n"
            "Last updated: 15/10/2019, 11:40.\n"
            "Available at: https://github.com/GTRONICK/QSS/blob/master/AMOLED.qss\n"
            "*/\n"
            "QMainWindow {\n"
            "    background-color:#000000;\n"
            "}\n"
            "QDialog {\n"
            "    background-color:#000000;\n"
            "}\n"
            "QColorDialog {\n"
            "    background-color:#000000;\n"
            "}\n"
            "QTextEdit {\n"
            "    background-color:#000000;\n"
            "    color: #a9b7c6;\n"
            "}\n"
            "QPlainTextEdit {\n"
            "    selection-background-color:#f39c12;\n"
            "    background-color:#000000;\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: transparent;\n"
            "    border-width: 1px;\n"
            "    color: #a9b7c6;\n"
            "}\n"
            "QPushButton{\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: transparent;\n"
            "    border-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: #a9b7c6;\n"
            "    padding: 2px;\n"
            "    background-color: #000000;\n"
            "}\n"
            "QPushButton::default{\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: #e67e22;\n"
            "    border-width: 1px;\n"
            "    color: #a9b7c6;\n"
            "    padding: 2px;\n"
            "    background-color: #000000;\n"
            "}\n"
            "QPushButton:hover{\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: #e67e22;\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: #FFFFFF;\n"
            "    padding-bottom: 2px;\n"
            "    background-color: #000000;\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: #e67e22;\n"
            "    border-bottom-width: 2px;\n"
            "    border-style: solid;\n"
            "    color: #e67e22;\n"
            "    padding-bottom: 1px;\n"
            "    background-color: #000000;\n"
            "}\n"
            "QPushButton:disabled{\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: transparent;\n"
            "    border-bottom-width: 2px;\n"
            "    border-style: solid;\n"
            "    color: #808086;\n"
            "    padding-bottom: 1px;\n"
            "    background-color: #000000;\n"
            "}\n"
            "QToolButton {\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: #e67e22;\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: #a9b7c6;\n"
            "    padding: 2px;\n"
            "    background-color: #000000;\n"
            "}\n"
            "QToolButton:hover{\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: #e67e22;\n"
            "    border-bottom-width: 2px;\n"
            "    border-style: solid;\n"
            "    color: #FFFFFF;\n"
            "    padding-bottom: 1px;\n"
            "    background-color: #000000;\n"
            "}\n"
            "QLineEdit {\n"
            "    border-width: 1px; border-radius: 4px;\n"
            "    border-color: rgb(58, 58, 58);\n"
            "    border-style: inset;\n"
            "    padding: 0 8px;\n"
            "    color: #a9b7c6;\n"
            "    background:#000000;\n"
            "    selection-background-color:#007b50;\n"
            "    selection-color: #FFFFFF;\n"
            "}\n"
            "QLabel {\n"
            "    color: #a9b7c6;\n"
            "}\n"
            "QLCDNumber {\n"
            "    color: #e67e22;\n"
            "}\n"
            "QProgressBar {\n"
            "    text-align: center;\n"
            "    color: rgb(240, 240, 240);\n"
            "    border-width: 1px; \n"
            "    border-radius: 10px;\n"
            "    border-color: rgb(58, 58, 58);\n"
            "    border-style: inset;\n"
            "    background-color:#000000;\n"
            "}\n"
            "QProgressBar::chunk {\n"
            "    background-color: #e67e22;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QMenu{\n"
            "    background-color:#000000;\n"
            "}\n"
            "QMenuBar {\n"
            "    background:rgb(0, 0, 0);\n"
            "    color: #a9b7c6;\n"
            "}\n"
            "QMenuBar::item {\n"
            "      spacing: 3px; \n"
            "    padding: 1px 4px;\n"
            "      background: transparent;\n"
            "}\n"
            "QMenuBar::item:selected { \n"
            "      border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: #e67e22;\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: #FFFFFF;\n"
            "    padding-bottom: 0px;\n"
            "    background-color: #000000;\n"
            "}\n"
            "QMenu::item:selected {\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: #e67e22;\n"
            "    border-bottom-color: transparent;\n"
            "    border-left-width: 2px;\n"
            "    color: #FFFFFF;\n"
            "    padding-left:15px;\n"
            "    padding-top:4px;\n"
            "    padding-bottom:4px;\n"
            "    padding-right:7px;\n"
            "    background-color:#000000;\n"
            "}\n"
            "QMenu::item {\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: transparent;\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: #a9b7c6;\n"
            "    padding-left:17px;\n"
            "    padding-top:4px;\n"
            "    padding-bottom:4px;\n"
            "    padding-right:7px;\n"
            "    background-color:#000000;\n"
            "}\n"
            "QTabWidget {\n"
            "    color:rgb(0,0,0);\n"
            "    background-color:#000000;\n"
            "}\n"
            "QTabWidget::pane {\n"
            "        border-color: rgb(77,77,77);\n"
            "        background-color:#000000;\n"
            "        border-style: solid;\n"
            "        border-width: 1px;\n"
            "        border-radius: 6px;\n"
            "}\n"
            "QTabBar::tab {\n"
            "    border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: transparent;\n"
            "    border-bottom-width: 1px;\n"
            "    border-style: solid;\n"
            "    color: #808086;\n"
            "    padding: 3px;\n"
            "    margin-left:3px;\n"
            "    background-color:#000000;\n"
            "}\n"
            "QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
            "      border-style: solid;\n"
            "    border-top-color: transparent;\n"
            "    border-right-color: transparent;\n"
            "    border-left-color: transparent;\n"
            "    border-bottom-color: #e67e22;\n"
            "    border-bottom-width: 2px;\n"
            "    border-style: solid;\n"
            "    color: #FFFFFF;\n"
            "    padding-left: 3px;\n"
            "    padding-bottom: 2px;\n"
            "    margin-left:3px;\n"
            "    background-color:#000000;\n"
            "}\n"
            "\n"
            "QCheckBox {\n"
            "    color: #a9b7c6;\n"
            "    padding: 2px;\n"
            "}\n"
            "QCheckBox:disabled {\n"
            "    color: #808086;\n"
            "    padding: 2px;\n"
            "}\n"
            "\n"
            "QCheckBox:hover {\n"
            "    border-radius:4px;\n"
            "    border-style:solid;\n"
            "    padding-left: 1px;\n"
            "    padding-right: 1px;\n"
            "    padding-bottom: 1px;\n"
            "    padding-top: 1px;\n"
            "    border-width:1px;\n"
            "    border-color: rgb(87, 97, 106);\n"
            "    background-color:#000000;\n"
            "}\n"
            "QCheckBox::indicator:checked {\n"
            "\n"
            "    height: 10px;\n"
            "    width: 10px;\n"
            "    border-style:solid;\n"
            "    border-width: 1px;\n"
            "    border-color: #e67e22;\n"
            "    color: #a9b7c6;\n"
            "    background-color: #e67e22;\n"
            "}\n"
            "QCheckBox::indicator:unchecked {\n"
            "\n"
            "    height: 10px;\n"
            "    width: 10px;\n"
            "    border-style:solid;\n"
            "    border-width: 1px;\n"
            "    border-color: #e67e22;\n"
            "    color: #a9b7c6;\n"
            "    background-color: transparent;\n"
            "}\n"
            "QRadioButton {\n"
            "    color: #a9b7c6;\n"
            "    background-color:#000000;\n"
            "    padding: 1px;\n"
            "}\n"
            "QRadioButton::indicator:checked {\n"
            "    height: 10px;\n"
            "    width: 10px;\n"
            "    border-style:solid;\n"
            "    border-radius:5px;\n"
            "    border-width: 1px;\n"
            "    border-color: #e67e22;\n"
            "    color: #a9b7c6;\n"
            "    background-color: #e67e22;\n"
            "}\n"
            "QRadioButton::indicator:!checked {\n"
            "    height: 10px;\n"
            "    width: 10px;\n"
            "    border-style:solid;\n"
            "    border-radius:5px;\n"
            "    border-width: 1px;\n"
            "    border-color: #e67e22;\n"
            "    color: #a9b7c6;\n"
            "    background-color: transparent;\n"
            "}\n"
            "QStatusBar {\n"
            "    color:#027f7f;\n"
            "}\n"
            "QSpinBox {\n"
            "    color: #a9b7c6;    \n"
            "    background-color:#000000;\n"
            "}\n"
            "QDoubleSpinBox {\n"
            "    color: #a9b7c6;    \n"
            "    background-color:#000000;\n"
            "}\n"
            "QTimeEdit {\n"
            "    color: #a9b7c6;    \n"
            "    background-color:#000000;\n"
            "}\n"
            "QDateTimeEdit {\n"
            "    color: #a9b7c6;    \n"
            "    background-color:#000000;\n"
            "}\n"
            "QDateEdit {\n"
            "    color: #a9b7c6;    \n"
            "    background-color:#000000;\n"
            "}\n"
            "QComboBox {\n"
            "    color: #a9b7c6;    \n"
            "    background: #1e1d23;\n"
            "}\n"
            "QComboBox:editable {\n"
            "    background: #1e1d23;\n"
            "    color: #a9b7c6;\n"
            "    selection-background-color:#000000;\n"
            "}\n"
            "QComboBox QAbstractItemView {\n"
            "    color: #a9b7c6;    \n"
            "    background: #1e1d23;\n"
            "    selection-color: #FFFFFF;\n"
            "    selection-background-color:#000000;\n"
            "}\n"
            "QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
            "    color: #a9b7c6;    \n"
            "    background: #1e1d23;\n"
            "}\n"
            "QFontComboBox {\n"
            "    color: #a9b7c6;    \n"
            "    background-color:#000000;\n"
            "}\n"
            "QToolBox {\n"
            "    color: #a9b7c6;\n"
            "    background-color:#000000;\n"
            "}\n"
            "QToolBox::tab {\n"
            "    color: #a9b7c6;\n"
            "    background-color:#000000;\n"
            "}\n"
            "QToolBox::tab:selected {\n"
            "    color: #FFFFFF;\n"
            "    background-color:#000000;\n"
            "}\n"
            "QScrollArea {\n"
            "    color: #FFFFFF;\n"
            "    background-color:#000000;\n"
            "}\n"
            "QSlider::groove:horizontal {\n"
            "    height: 5px;\n"
            "    background: #e67e22;\n"
            "}\n"
            "QSlider::groove:vertical {\n"
            "    width: 5px;\n"
            "    background: #e67e22;\n"
            "}\n"
            "QSlider::handle:horizontal {\n"
            "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
            "    border: 1px solid #5c5c5c;\n"
            "    width: 14px;\n"
            "    margin: -5px 0;\n"
            "    border-radius: 7px;\n"
            "}\n"
            "QSlider::handle:vertical {\n"
            "    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
            "    border: 1px solid #5c5c5c;\n"
            "    height: 14px;\n"
            "    margin: 0 -5px;\n"
            "    border-radius: 7px;\n"
            "}\n"
            "QSlider::add-page:horizontal {\n"
            "    background: white;\n"
            "}\n"
            "QSlider::add-page:vertical {\n"
            "    background: white;\n"
            "}\n"
            "QSlider::sub-page:horizontal {\n"
            "    background: #e67e22;\n"
            "}\n"
            "QSlider::sub-page:vertical {\n"
            "    background: #e67e22;\n"
            "}\n"
            "QScrollBar:horizontal {\n"
            "    max-height: 20px;\n"
            "    background: rgb(0,0,0);\n"
            "    border: 1px transparent grey;\n"
            "    margin: 0px 20px 0px 20px;\n"
            "}\n"
            "QScrollBar::handle:horizontal {\n"
            "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
            "    border-style: solid;\n"
            "    border-width: 1px;\n"
            "    border-color: rgb(0,0,0);\n"
            "    min-width: 25px;\n"
            "}\n"
            "QScrollBar::handle:horizontal:hover {\n"
            "    background: rgb(230, 126, 34);\n"
            "    border-style: solid;\n"
            "    border-width: 1px;\n"
            "    border-color: rgb(0,0,0);\n"
            "    min-width: 25px;\n"
            "}\n"
            "QScrollBar::add-line:horizontal {\n"
            "      border: 1px solid;\n"
            "      border-color: rgb(0,0,0);\n"
            "      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
            "      width: 20px;\n"
            "      subcontrol-position: right;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::add-line:horizontal:hover {\n"
            "      border: 1px solid;\n"
            "      border-color: rgb(0,0,0);\n"
            "    border-radius: 8px;\n"
            "      background: rgb(230, 126, 34);\n"
            "      height: 16px;\n"
            "      width: 16px;\n"
            "      subcontrol-position: right;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::add-line:horizontal:pressed {\n"
            "      border: 1px solid;\n"
            "      border-color: grey;\n"
            "    border-radius: 8px;\n"
            "      background: rgb(230, 126, 34);\n"
            "      height: 16px;\n"
            "      width: 16px;\n"
            "      subcontrol-position: right;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::sub-line:horizontal {\n"
            "      border: 1px solid;\n"
            "      border-color: rgb(0,0,0);\n"
            "      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
            "      width: 20px;\n"
            "      subcontrol-position: left;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::sub-line:horizontal:hover {\n"
            "      border: 1px solid;\n"
            "      border-color: rgb(0,0,0);\n"
            "    border-radius: 8px;\n"
            "      background: rgb(230, 126, 34);\n"
            "      height: 16px;\n"
            "      width: 16px;\n"
            "      subcontrol-position: left;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::sub-line:horizontal:pressed {\n"
            "      border: 1px solid;\n"
            "      border-color: grey;\n"
            "    border-radius: 8px;\n"
            "      background: rgb(230, 126, 34);\n"
            "      height: 16px;\n"
            "      width: 16px;\n"
            "      subcontrol-position: left;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::left-arrow:horizontal {\n"
            "      border: 1px transparent grey;\n"
            "      border-radius: 3px;\n"
            "      width: 6px;\n"
            "      height: 6px;\n"
            "     background: rgb(0,0,0);\n"
            "}\n"
            "QScrollBar::right-arrow:horizontal {\n"
            "    border: 1px transparent grey;\n"
            "    border-radius: 3px;\n"
            "      width: 6px;\n"
            "      height: 6px;\n"
            "     background: rgb(0,0,0);\n"
            "}\n"
            "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
            "     background: none;\n"
            "} \n"
            "QScrollBar:vertical {\n"
            "    max-width: 20px;\n"
            "    background: rgb(0,0,0);\n"
            "    border: 1px transparent grey;\n"
            "    margin: 20px 0px 20px 0px;\n"
            "}\n"
            "QScrollBar::add-line:vertical {\n"
            "    border: 1px solid;\n"
            "      border-color: rgb(0,0,0);\n"
            "      background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
            "      height: 20px;\n"
            "      subcontrol-position: bottom;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::add-line:vertical:hover {\n"
            "      border: 1px solid;\n"
            "      border-color: rgb(0,0,0);\n"
            "    border-radius: 8px;\n"
            "      background: rgb(230, 126, 34);\n"
            "      height: 16px;\n"
            "      width: 16px;\n"
            "      subcontrol-position: bottom;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::add-line:vertical:pressed {\n"
            "      border: 1px solid;\n"
            "      border-color: grey;\n"
            "    border-radius: 8px;\n"
            "      background: rgb(230, 126, 34);\n"
            "      height: 16px;\n"
            "      width: 16px;\n"
            "      subcontrol-position: bottom;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::sub-line:vertical {\n"
            "      border: 1px solid;\n"
            "      border-color: rgb(0,0,0);\n"
            "    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
            "      height: 20px;\n"
            "      subcontrol-position: top;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::sub-line:vertical:hover {\n"
            "      border: 1px solid;\n"
            "      border-color: rgb(0,0,0);\n"
            "    border-radius: 8px;\n"
            "      background: rgb(230, 126, 34);\n"
            "      height: 16px;\n"
            "      width: 16px;\n"
            "      subcontrol-position: top;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "QScrollBar::sub-line:vertical:pressed {\n"
            "      border: 1px solid;\n"
            "      border-color: grey;\n"
            "    border-radius: 8px;\n"
            "      background: rgb(230, 126, 34);\n"
            "      height: 16px;\n"
            "      width: 16px;\n"
            "      subcontrol-position: top;\n"
            "      subcontrol-origin: margin;\n"
            "}\n"
            "    QScrollBar::handle:vertical {\n"
            "    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
            "    border-style: solid;\n"
            "    border-width: 1px;\n"
            "    border-color: rgb(0,0,0);\n"
            "    min-height: 25px;\n"
            "}\n"
            "QScrollBar::handle:vertical:hover {\n"
            "    background: rgb(230, 126, 34);\n"
            "    border-style: solid;\n"
            "    border-width: 1px;\n"
            "    border-color: rgb(0,0,0);\n"
            "    min-heigth: 25px;\n"
            "}\n"
            "QScrollBar::up-arrow:vertical {\n"
            "    border: 1px transparent grey;\n"
            "    border-radius: 3px;\n"
            "      width: 6px;\n"
            "      height: 6px;\n"
            "     background: rgb(0,0,0);\n"
            "}\n"
            "QScrollBar::down-arrow:vertical {\n"
            "      border: 1px transparent grey;\n"
            "      border-radius: 3px;\n"
            "      width: 6px;\n"
            "      height: 6px;\n"
            "     background: rgb(0,0,0);\n"
            "}\n"
            "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
            "      background: none;\n"
            "}\n"
            ""
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(984, 1172))
        self.centralwidget.setObjectName("centralwidget")
        self.app_pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.app_pages.setGeometry(QtCore.QRect(0, 0, 981, 1171))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_pages.sizePolicy().hasHeightForWidth())
        self.app_pages.setSizePolicy(sizePolicy)
        self.app_pages.setMinimumSize(QtCore.QSize(941, 1151))
        self.app_pages.setObjectName("app_pages")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.login_page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(180, 400, 631, 271))
        self.gridLayoutWidget.setMinimumSize(QtCore.QSize(631, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.login_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.login_grid.setContentsMargins(0, 0, 50, 0)
        self.login_grid.setVerticalSpacing(0)
        self.login_grid.setObjectName("login_grid")
        self.login_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.login_input.setObjectName("login_input")
        self.login_grid.addWidget(self.login_input, 1, 1, 1, 1)
        self.login_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.login_label.setMinimumSize(QtCore.QSize(75, 20))
        self.login_label.setObjectName("login_label")
        self.login_grid.addWidget(self.login_label, 1, 0, 1, 1)
        self.submit_data = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.submit_data.setMinimumSize(QtCore.QSize(75, 23))
        self.submit_data.setObjectName("submit_data")
        self.login_grid.addWidget(self.submit_data, 3, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.password_label.setMinimumSize(QtCore.QSize(75, 20))
        self.password_label.setObjectName("password_label")
        self.login_grid.addWidget(self.password_label, 2, 0, 1, 1)
        self.password_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password_input.setObjectName("password_input")
        self.login_grid.addWidget(self.password_input, 2, 1, 1, 1)
        self.register_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.register_btn.setObjectName("register_btn")
        self.login_grid.addWidget(self.register_btn, 4, 0, 1, 1)
        self.app_pages.addWidget(self.login_page)
        self.image_page = QtWidgets.QWidget()
        self.image_page.setObjectName("image_page")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.image_page)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 961, 1151))
        self.gridLayoutWidget_2.setMinimumSize(QtCore.QSize(921, 1131))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.image_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.image_grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.image_grid.setContentsMargins(0, 0, 0, 0)
        self.image_grid.setObjectName("image_grid")
        self.next_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.next_btn.setMinimumSize(QtCore.QSize(302, 23))
        self.next_btn.setObjectName("next_btn")
        self.image_grid.addWidget(self.next_btn, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            303, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.image_grid.addItem(spacerItem, 0, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.save_btn.setMinimumSize(QtCore.QSize(302, 23))
        self.save_btn.setObjectName("save_btn")
        self.image_grid.addWidget(self.save_btn, 4, 0, 1, 1)
        self.pepe_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pepe_btn.setMinimumSize(QtCore.QSize(302, 23))
        self.pepe_btn.setObjectName("pepe_btn")
        self.image_grid.addWidget(self.pepe_btn, 4, 2, 1, 1)
        self.rescan_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.rescan_btn.setMinimumSize(QtCore.QSize(303, 23))
        self.rescan_btn.setObjectName("rescan_btn")
        self.image_grid.addWidget(self.rescan_btn, 3, 1, 1, 1)
        self.previous_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.previous_btn.setMinimumSize(QtCore.QSize(302, 23))
        self.previous_btn.setObjectName("previous_btn")
        self.image_grid.addWidget(self.previous_btn, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            303, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.image_grid.addItem(spacerItem1, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.image_grid.addWidget(self.progressBar, 0, 0, 1, 1)
        self.image_view = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.image_view.setMinimumSize(QtCore.QSize(959, 970))
        self.image_view.setObjectName("image_view")
        self.image_grid.addWidget(self.image_view, 1, 0, 1, 3)
        self.scrape_menu_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.scrape_menu_btn.setObjectName("scrape_menu_btn")
        self.image_grid.addWidget(self.scrape_menu_btn, 4, 1, 1, 1)
        self.app_pages.addWidget(self.image_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 961, 1151))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrape_command_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.scrape_command_btn.setObjectName("scrape_command_btn")
        self.gridLayout.addWidget(self.scrape_command_btn, 22, 1, 1, 1)
        self.asp_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.asp_checkbox.setObjectName("asp_checkbox")
        self.gridLayout.addWidget(self.asp_checkbox, 10, 19, 1, 1)
        self.vm_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.vm_checkbox.setObjectName("vm_checkbox")
        self.gridLayout.addWidget(self.vm_checkbox, 6, 0, 1, 1)
        self.vrpg_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.vrpg_checkbox.setObjectName("vrpg_checkbox")
        self.gridLayout.addWidget(self.vrpg_checkbox, 7, 0, 1, 1)
        self.vip_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.vip_checkbox.setObjectName("vip_checkbox")
        self.gridLayout.addWidget(self.vip_checkbox, 8, 0, 1, 1)
        self.lgbt_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.lgbt_checkbox.setObjectName("lgbt_checkbox")
        self.gridLayout.addWidget(self.lgbt_checkbox, 9, 0, 1, 1)
        self.biz_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.biz_checkbox.setObjectName("biz_checkbox")
        self.gridLayout.addWidget(self.biz_checkbox, 11, 0, 1, 1)
        self.co_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.co_checkbox.setObjectName("co_checkbox")
        self.gridLayout.addWidget(self.co_checkbox, 12, 0, 1, 1)
        self.an_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.an_checkbox.setObjectName("an_checkbox")
        self.gridLayout.addWidget(self.an_checkbox, 10, 0, 1, 1)
        self.int_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.int_checkbox.setObjectName("int_checkbox")
        self.gridLayout.addWidget(self.int_checkbox, 14, 0, 1, 1)
        self.fit_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.fit_checkbox.setObjectName("fit_checkbox")
        self.gridLayout.addWidget(self.fit_checkbox, 13, 0, 1, 1)
        self.mlp_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.mlp_checkbox.setObjectName("mlp_checkbox")
        self.gridLayout.addWidget(self.mlp_checkbox, 15, 0, 1, 1)
        self.p_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.p_checkbox.setObjectName("p_checkbox")
        self.gridLayout.addWidget(self.p_checkbox, 5, 0, 1, 1)
        self.ck_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.ck_checkbox.setObjectName("ck_checkbox")
        self.gridLayout.addWidget(self.ck_checkbox, 11, 19, 1, 1)
        self.tvr_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.tvr_checkbox.setObjectName("tvr_checkbox")
        self.gridLayout.addWidget(self.tvr_checkbox, 18, 19, 1, 1)
        self.his_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.his_checkbox.setObjectName("his_checkbox")
        self.gridLayout.addWidget(self.his_checkbox, 13, 19, 1, 1)
        self.tv_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.tv_checkbox.setObjectName("tv_checkbox")
        self.gridLayout.addWidget(self.tv_checkbox, 19, 0, 1, 1)
        self.a_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.a_checkbox.setObjectName("a_checkbox")
        self.gridLayout.addWidget(self.a_checkbox, 3, 0, 1, 1)
        self.qst_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.qst_checkbox.setObjectName("qst_checkbox")
        self.gridLayout.addWidget(self.qst_checkbox, 17, 0, 1, 1)
        self.news_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.news_checkbox.setObjectName("news_checkbox")
        self.gridLayout.addWidget(self.news_checkbox, 16, 0, 1, 1)
        self.tg_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.tg_checkbox.setObjectName("tg_checkbox")
        self.gridLayout.addWidget(self.tg_checkbox, 18, 0, 1, 1)
        self.wsr_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.wsr_checkbox.setObjectName("wsr_checkbox")
        self.gridLayout.addWidget(self.wsr_checkbox, 20, 0, 1, 1)
        self.o_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.o_checkbox.setObjectName("o_checkbox")
        self.gridLayout.addWidget(self.o_checkbox, 4, 19, 1, 1)
        self.gd_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.gd_checkbox.setObjectName("gd_checkbox")
        self.gridLayout.addWidget(self.gd_checkbox, 13, 1, 1, 1)
        self.diy_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.diy_checkbox.setObjectName("diy_checkbox")
        self.gridLayout.addWidget(self.diy_checkbox, 12, 1, 1, 1)
        self.jp_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.jp_checkbox.setObjectName("jp_checkbox")
        self.gridLayout.addWidget(self.jp_checkbox, 14, 1, 1, 1)
        self.v_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.v_checkbox.setObjectName("v_checkbox")
        self.gridLayout.addWidget(self.v_checkbox, 5, 1, 1, 1)
        self.sp_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.sp_checkbox.setObjectName("sp_checkbox")
        self.gridLayout.addWidget(self.sp_checkbox, 17, 19, 1, 1)
        self.fa_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.fa_checkbox.setObjectName("fa_checkbox")
        self.gridLayout.addWidget(self.fa_checkbox, 12, 19, 1, 1)
        self.mu_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.mu_checkbox.setObjectName("mu_checkbox")
        self.gridLayout.addWidget(self.mu_checkbox, 15, 1, 1, 1)
        self.m_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.m_checkbox.setObjectName("m_checkbox")
        self.gridLayout.addWidget(self.m_checkbox, 4, 1, 1, 1)
        self.out_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.out_checkbox.setObjectName("out_checkbox")
        self.gridLayout.addWidget(self.out_checkbox, 16, 1, 1, 1)
        self.vmg_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.vmg_checkbox.setObjectName("vmg_checkbox")
        self.gridLayout.addWidget(self.vmg_checkbox, 6, 1, 1, 1)
        self.g_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.g_checkbox.setObjectName("g_checkbox")
        self.gridLayout.addWidget(self.g_checkbox, 3, 19, 1, 1)
        self.lit_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.lit_checkbox.setObjectName("lit_checkbox")
        self.gridLayout.addWidget(self.lit_checkbox, 14, 19, 1, 1)
        self.n_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.n_checkbox.setObjectName("n_checkbox")
        self.gridLayout.addWidget(self.n_checkbox, 15, 19, 1, 1)
        self.vr_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.vr_checkbox.setObjectName("vr_checkbox")
        self.gridLayout.addWidget(self.vr_checkbox, 6, 19, 1, 1)
        self.cgi_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cgi_checkbox.setObjectName("cgi_checkbox")
        self.gridLayout.addWidget(self.cgi_checkbox, 11, 1, 1, 1)
        self.vst_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.vst_checkbox.setObjectName("vst_checkbox")
        self.gridLayout.addWidget(self.vst_checkbox, 7, 1, 1, 1)
        self.return_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.return_btn.setObjectName("return_btn")
        self.gridLayout.addWidget(self.return_btn, 22, 0, 1, 1)
        self.k_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.k_checkbox.setObjectName("k_checkbox")
        self.gridLayout.addWidget(self.k_checkbox, 4, 0, 1, 1)
        self.three_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.three_checkbox.setObjectName("three_checkbox")
        self.gridLayout.addWidget(self.three_checkbox, 9, 1, 1, 1)
        self.qa_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.qa_checkbox.setObjectName("qa_checkbox")
        self.gridLayout.addWidget(self.qa_checkbox, 8, 1, 1, 1)
        self.pol_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.pol_checkbox.setObjectName("pol_checkbox")
        self.gridLayout.addWidget(self.pol_checkbox, 16, 19, 1, 1)
        self.s4s_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.s4s_checkbox.setObjectName("s4s_checkbox")
        self.gridLayout.addWidget(self.s4s_checkbox, 10, 1, 1, 1)
        self.x_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.x_checkbox.setObjectName("x_checkbox")
        self.gridLayout.addWidget(self.x_checkbox, 21, 1, 1, 1)
        self.b_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.b_checkbox.setObjectName("b_checkbox")
        self.gridLayout.addWidget(self.b_checkbox, 20, 1, 1, 1)
        self.remember_boards_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.remember_boards_btn.setObjectName("remember_boards_btn")
        self.gridLayout.addWidget(self.remember_boards_btn, 22, 19, 1, 1)
        self.w_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.w_checkbox.setObjectName("w_checkbox")
        self.gridLayout.addWidget(self.w_checkbox, 7, 19, 1, 1)
        self.vg_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.vg_checkbox.setObjectName("vg_checkbox")
        self.gridLayout.addWidget(self.vg_checkbox, 5, 19, 1, 1)
        self.wsg_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.wsg_checkbox.setObjectName("wsg_checkbox")
        self.gridLayout.addWidget(self.wsg_checkbox, 19, 19, 1, 1)
        self.toy_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.toy_checkbox.setObjectName("toy_checkbox")
        self.gridLayout.addWidget(self.toy_checkbox, 18, 1, 1, 1)
        self.adv_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.adv_checkbox.setObjectName("adv_checkbox")
        self.gridLayout.addWidget(self.adv_checkbox, 9, 19, 1, 1)
        self.cm_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cm_checkbox.setObjectName("cm_checkbox")
        self.gridLayout.addWidget(self.cm_checkbox, 8, 19, 1, 1)
        self.vp_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.vp_checkbox.setObjectName("vp_checkbox")
        self.gridLayout.addWidget(self.vp_checkbox, 19, 1, 1, 1)
        self.sci_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.sci_checkbox.setObjectName("sci_checkbox")
        self.gridLayout.addWidget(self.sci_checkbox, 17, 1, 1, 1)
        self.c_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.c_checkbox.setObjectName("c_checkbox")
        self.gridLayout.addWidget(self.c_checkbox, 3, 1, 1, 1)
        self.r9k_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.r9k_checkbox.setObjectName("r9k_checkbox")
        self.gridLayout.addWidget(self.r9k_checkbox, 20, 19, 1, 1)
        self.purge_unsaved_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.purge_unsaved_btn.setObjectName("purge_unsaved_btn")
        self.gridLayout.addWidget(self.purge_unsaved_btn, 0, 0, 1, 1)
        self.purge_pepes_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.purge_pepes_btn.setObjectName("purge_pepes_btn")
        self.gridLayout.addWidget(self.purge_pepes_btn, 0, 19, 1, 1)
        self.purge_saved_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.purge_saved_btn.setObjectName("purge_saved_btn")
        self.gridLayout.addWidget(self.purge_saved_btn, 0, 1, 1, 1)
        self.download_saved_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.download_saved_btn.setObjectName("download_saved_btn")
        self.gridLayout.addWidget(self.download_saved_btn, 2, 1, 1, 1)
        self.download_pepes_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.download_pepes_btn.setObjectName("download_pepes_btn")
        self.gridLayout.addWidget(self.download_pepes_btn, 2, 19, 1, 1)
        self.upload_pepes_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.upload_pepes_btn.setObjectName("upload_pepes_btn")
        self.gridLayout.addWidget(self.upload_pepes_btn, 1, 19, 1, 1)
        self.not_yet = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.not_yet.setObjectName("not_yet")
        self.gridLayout.addWidget(self.not_yet, 23, 0, 1, 1)
        self.upload_saved_btn = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.upload_saved_btn.setObjectName("upload_saved_btn")
        self.gridLayout.addWidget(self.upload_saved_btn, 1, 1, 1, 1)
        self.app_pages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(210, 220, 451, 311))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.username_field = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.username_field.setObjectName("username_field")
        self.gridLayout_2.addWidget(self.username_field, 0, 1, 1, 1)
        self.email_field = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.email_field.setObjectName("email_field")
        self.gridLayout_2.addWidget(self.email_field, 2, 1, 1, 1)
        self.password_field = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.password_field.setObjectName("password_field")
        self.gridLayout_2.addWidget(self.password_field, 1, 1, 1, 1)
        self.nickname_field = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.nickname_field.setObjectName("nickname_field")
        self.gridLayout_2.addWidget(self.nickname_field, 3, 1, 1, 1)
        self.username_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.username_label.setObjectName("username_label")
        self.gridLayout_2.addWidget(self.username_label, 0, 0, 1, 1)
        self.email_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.email_label.setObjectName("email_label")
        self.gridLayout_2.addWidget(self.email_label, 2, 0, 1, 1)
        self.nickname_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.nickname_label.setObjectName("nickname_label")
        self.gridLayout_2.addWidget(self.nickname_label, 3, 0, 1, 1)
        self.password_label_register = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.password_label_register.setObjectName("password_label_register")
        self.gridLayout_2.addWidget(self.password_label_register, 1, 0, 1, 1)
        self.send_data = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.send_data.setObjectName("send_data")
        self.gridLayout_2.addWidget(self.send_data, 4, 0, 1, 1)
        self.return_btn_register = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.return_btn_register.setObjectName("return_btn_register")
        self.gridLayout_2.addWidget(self.return_btn_register, 5, 0, 1, 1)
        self.app_pages.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.app_pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label.setText(_translate("MainWindow", "Login"))
        self.submit_data.setText(_translate("MainWindow", "Login"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.register_btn.setText(_translate("MainWindow", "Register"))
        self.next_btn.setText(_translate("MainWindow", "Next"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.pepe_btn.setText(_translate("MainWindow", "Mark PEPE"))
        self.rescan_btn.setText(_translate("MainWindow", "Rescan"))
        self.previous_btn.setText(_translate("MainWindow", "Previous"))
        self.image_view.setText(_translate("MainWindow", "TextLabel"))
        self.scrape_menu_btn.setText(_translate("MainWindow", "Scrape Menu"))
        self.scrape_command_btn.setText(_translate("MainWindow", "Scrape"))
        self.asp_checkbox.setText(_translate("MainWindow", "/asp/"))
        self.vm_checkbox.setText(_translate("MainWindow", "/vm/"))
        self.vrpg_checkbox.setText(_translate("MainWindow", "/vrpg/"))
        self.vip_checkbox.setText(_translate("MainWindow", "/vip/"))
        self.lgbt_checkbox.setText(_translate("MainWindow", "/lgbt/"))
        self.biz_checkbox.setText(_translate("MainWindow", "/biz/"))
        self.co_checkbox.setText(_translate("MainWindow", "/co/"))
        self.an_checkbox.setText(_translate("MainWindow", "/an/"))
        self.int_checkbox.setText(_translate("MainWindow", "/int/"))
        self.fit_checkbox.setText(_translate("MainWindow", "/fit/"))
        self.mlp_checkbox.setText(_translate("MainWindow", "/mlp/"))
        self.p_checkbox.setText(_translate("MainWindow", "/p/"))
        self.ck_checkbox.setText(_translate("MainWindow", "/ck/"))
        self.tvr_checkbox.setText(_translate("MainWindow", "/trv/"))
        self.his_checkbox.setText(_translate("MainWindow", "/his/"))
        self.tv_checkbox.setText(_translate("MainWindow", "/tv/"))
        self.a_checkbox.setText(_translate("MainWindow", "/a/"))
        self.qst_checkbox.setText(_translate("MainWindow", "/qst/"))
        self.news_checkbox.setText(_translate("MainWindow", "/news/"))
        self.tg_checkbox.setText(_translate("MainWindow", "/tg/"))
        self.wsr_checkbox.setText(_translate("MainWindow", "/wsr/"))
        self.o_checkbox.setText(_translate("MainWindow", "/o/"))
        self.gd_checkbox.setText(_translate("MainWindow", "/gd/"))
        self.diy_checkbox.setText(_translate("MainWindow", "/diy/"))
        self.jp_checkbox.setText(_translate("MainWindow", "/jp/"))
        self.v_checkbox.setText(_translate("MainWindow", "/v/"))
        self.sp_checkbox.setText(_translate("MainWindow", "/sp/"))
        self.fa_checkbox.setText(_translate("MainWindow", "/fa/"))
        self.mu_checkbox.setText(_translate("MainWindow", "/mu/"))
        self.m_checkbox.setText(_translate("MainWindow", "/m/"))
        self.out_checkbox.setText(_translate("MainWindow", "/out/"))
        self.vmg_checkbox.setText(_translate("MainWindow", "/vmg/"))
        self.g_checkbox.setText(_translate("MainWindow", "/g/"))
        self.lit_checkbox.setText(_translate("MainWindow", "/lit/"))
        self.n_checkbox.setText(_translate("MainWindow", "/n/"))
        self.vr_checkbox.setText(_translate("MainWindow", "/vr/"))
        self.cgi_checkbox.setText(_translate("MainWindow", "/cgi/"))
        self.vst_checkbox.setText(_translate("MainWindow", "/vst/"))
        self.return_btn.setText(_translate("MainWindow", "Back to Images"))
        self.k_checkbox.setText(_translate("MainWindow", "/k/"))
        self.three_checkbox.setText(_translate("MainWindow", "/3/"))
        self.qa_checkbox.setText(_translate("MainWindow", "/qa/"))
        self.pol_checkbox.setText(_translate("MainWindow", "/pol/"))
        self.s4s_checkbox.setText(_translate("MainWindow", "/s4s/"))
        self.x_checkbox.setText(_translate("MainWindow", "/x/"))
        self.b_checkbox.setText(_translate("MainWindow", "/b/"))
        self.remember_boards_btn.setText(_translate("MainWindow", "Remember Boards"))
        self.w_checkbox.setText(_translate("MainWindow", "/w/"))
        self.vg_checkbox.setText(_translate("MainWindow", "/vg/"))
        self.wsg_checkbox.setText(_translate("MainWindow", "/wsg/"))
        self.toy_checkbox.setText(_translate("MainWindow", "/toy/"))
        self.adv_checkbox.setText(_translate("MainWindow", "/adv/"))
        self.cm_checkbox.setText(_translate("MainWindow", "/cm/"))
        self.vp_checkbox.setText(_translate("MainWindow", "/vp/"))
        self.sci_checkbox.setText(_translate("MainWindow", "/sci/"))
        self.c_checkbox.setText(_translate("MainWindow", "/c/"))
        self.r9k_checkbox.setText(_translate("MainWindow", "/r9k/"))
        self.purge_unsaved_btn.setText(_translate("MainWindow", "Purge Unsaved"))
        self.purge_pepes_btn.setText(_translate("MainWindow", "Purge Pepes"))
        self.purge_saved_btn.setText(_translate("MainWindow", "Purge Saved"))
        self.download_saved_btn.setText(_translate("MainWindow", "Download Saved"))
        self.download_pepes_btn.setText(_translate("MainWindow", "Download Pepes"))
        self.upload_pepes_btn.setText(_translate("MainWindow", "Upload Pepes"))
        self.not_yet.setText(_translate("MainWindow", "it's a pepperoni secret"))
        self.upload_saved_btn.setText(_translate("MainWindow", "Upload Saved"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.email_label.setText(_translate("MainWindow", "Email"))
        self.nickname_label.setText(_translate("MainWindow", "Nickname"))
        self.password_label_register.setText(_translate("MainWindow", "Password"))
        self.send_data.setText(_translate("MainWindow", "Register"))
        self.return_btn_register.setText(_translate("MainWindow", "Return"))
